### ISSUE TITLE
Contributing, reporting, and support

### ISSUE THREAD

**Issue by mefuller** [andr1976/HydDown#57]
For review openjournals/joss-reviews#3695 :

Other than the default github features (author identification, issue tracker, pull requests), there is no explicit mention in the README or elsewhere as to how one contributes to the software, reports, bugs (and requests enhancements) or asks for support.
Given the nature of the github interface, I do not think this is strictly required, but it would be beneficial to add text on this to the README file

**Comment by andr1976** [comment]
@mefuller, Good point I will create a contributing.md file and populate it appropriately ASAP

**Comment by andr1976** [comment]
@mefuller , if you accept/agree , please close this issue
