### ISSUE TITLE
Usage and examples

### ISSUE THREAD

**Issue by mefuller** [andr1976/HydDown#59]
While the manual provides additional information about where to find various main programs, some clarification in the README and comments in the code are strongly needed to make the software more intuitive
(Don't do anything yet, I am still working on the manual)

**Comment by mefuller** [comment]
The exact meaning/definition of specified h, constant U, and constant Q heat flux is lacking (manual.md).

I am also making a number of edits to spelling and grammar in the manual, which I will submit as a PR.

**Comment by andr1976** [comment]
I have tried to address the meaning of specified h/ const U, constant Q in the manual

**Comment by mefuller** [comment]
@andr1976  I'll take a look shortly.
Going forward, you may want to make such changes in a separate branch and submit a PR and request me (or another reviewer) so that the differences are obvious and easily commented upon

**Comment by andr1976** [comment]
@mefuller, noted I have created a separate branch https://github.com/andr1976/HydDown/tree/revise-mefuller to address e.g. comments in the code / doc strings etc. I will let you know when to review

**Comment by andr1976** [comment]
@mefuller , I have added you as collaborator in order to be able to invite you to review oull requests. Once you accept I will send a PR for review

**Comment by bocklund** [comment]
I also think it would be nice to have something like a quickstart. The instructions in the README and manual to


> Run the code as simple as:
> 
> ```
> python main.py input.yml
> ```

does not work if users install from pip instead of from the source tree, since they don't have access to those files. The instructions could be more clear for users who may not be very experienced and don't know where to find the `input.yml` and `main.py` files.

**Comment by andr1976** [comment]
@mefuller, let me know if you have more comments I should address or revise the paper/code, also consider closing this issue.

**Comment by mefuller** [comment]
Everything looks good
