### ISSUE TITLE
Installation instructions do not include instructions to install dependencies

### ISSUE THREAD

**Issue by bocklund** [andr1976/HydDown#63]
The installation instructions in the README say to `pip install hyddown`, but the runtime dependencies are not included.

I was able to find the `requirements.txt` and install them manually, but I would suggest either setting up the distribution so pip can install the dependencies automatically, or include installing the dependencies in the installation instructions.

**Comment by andr1976** [comment]
@bocklund thanks for spotting these inconsistencies. I have not yet uploaded a new package to pypi, but will do that when the review is close to final. However, automatic installation of dependencies can be verified by: 

      pip uninstall hyddown cerberus pyyaml

.. just uninstalling a few of the dependencies to have them installed again
and then from the source root folder (using the updated setup cfg)

     pip install .

**Comment by bocklund** [comment]
Thanks, it works well for me!
