### ISSUE TITLE
Incomplete run of the program

### ISSUE THREAD

**Issue by rei148** [andr1976/HydDown#81]
Hello,

when I run the program, it does not complete the execution. You can see 1999/2000 in the console, but I do not know exactly what it means. See the image. Therefore I cannot extract values from it and use it how I wish. Any idea on how to solve this problem?

<img width="1434" alt="Captura de Pantalla 2023-01-19 a las 10 31 01" src="https://user-images.githubusercontent.com/123067070/213406630-8014fc74-fcde-4953-948b-f95abb98b25e.png">

**Comment by rei148** [comment]
Hi, thank you very much for you answer. 

I am using the "fillingH2.yml" from the examples you added to the program. Actually I can now take the pressure and temperature arrays from the program. However, I do not know if there is a problem with that incomplete "1999/2000", that you can see on the picture. For now it seems ok.

On the other hand, I have noticed, that your program uses the initial temperature of the gas in the tank as the inlet temperature of the entering gas, for the case of filling and "energy balance" heat method. Please correct me if I am wrong. I am thinking about extending your code to also make inlet temperatures different from initial tank temperatures possible. Would you like to receive the results?

Again, thank you very much for you answer.

**Comment by andr1976** [comment]
No, its proably the iterator that is offset. I will look into it ASAP. But if you can get the results it should be ok
